less(0,s(X)):-nat(X).
less(0,0).
less(s(X),s(Y)):-less(X,Y).
menor(s(X),s(Y)):-menor(X,Y).
menor(0,s(X)):-nat(X).
eq(s(X),s(Y)):-eq(X,Y).
eq(0,0).
nat(0).
nat(s(X)):-nat(X).
dim(s(X)):-dim(X).
dim(s(0)).
pieza(X,Y,Z,C) :- dim(X),dim(Y),dim(Z),color(C).
color(r).
color(am).
color(a).
color(v).
esTorre([G|K]):-
	esMayor(G,K).
esMayor(pieza(X,Y,Z,C),[pieza(Q,W,E,R)|K]):-
	less(X,Q),
	less(Z,E),
	pieza(X,Y,Z,C),
	pieza(Q,W,E,R),
	esMayor(pieza(Q,W,E,R),K).

esMayor(pieza(X,Y,Z,C),[]):-
	pieza(X,Y,Z,C).	
alturaTorre(T,A):-
	esTorre(T),
	nat(A),
	sumaAltura(T,A).
sumaAltura([S|B],A):-
	sumRec(S,B,0,A).
sumRec(pieza(X,Y,Z,C),[pieza(Q,W,E,R)|K],P,A):-
	sum(Y,P,J),
	pieza(X,Y,Z,C),
	pieza(Q,W,E,R),
	sumRec(pieza(Q,W,E,R),K,J,A).

sumRec(pieza(X,Y,Z,C),[],P,A):-
	pieza(X,Y,Z,C),
	sum(Y,P,J),
	eq(J,A).
sum(0,Y,Y):-
	nat(Y).
sum(s(X),Y,s(Z)):-
	sum(X,Y,Z).
coloresTorre(L1,L2):-
	esTorre(L1),
	colores(L1,L2).
colores([pieza(X,Y,Z,C)|R],[V|B]):-
	pieza(X,Y,Z,C),
	C=V,
	colores(R,B).
colores([],[]).
coloresIncluidos(L,T):-
	esTorre(L),
	esTorre(T),
	colorSub(L,T,T).
colorSub([pieza(_,_,_,X)|Xs],[pieza(_,_,_,X)|_],T):-
	colorSub(Xs,T,T).
colorSub(A,[_|Ys],T):-
	colorSub(A,Ys,T).

colorSub([],_,_).
esPar(s(s(X))):-
	esPar(X).
esPar(0).
esEdificioPar([A|B]):-
	recFilaPar(A,0),
	esEdificioPar(B).
esEdificioPar([]).

recFilaPar([r|A],C):-
	recFilaPar(A,s(C)).
recFilaPar([am|A],C):-
	recFilaPar(A,s(C)).
recFilaPar([a|A],C):-
	recFilaPar(A,s(C)).
recFilaPar([v|A],C):-
	recFilaPar(A,s(C)).
recFilaPar([b|A],C):-
	recFilaPar(A,C).
recFilaPar([],C):-
	esPar(C).
not(Var):-
	Var,!,fail.
not(_).

esEdificioPiramide([L1,L2|R]):-
	pirComp(L1,L2),
	esEdificioPiramide([L2|R]).
esEdificioPiramide([_|[]]).
pirComp(L1,L2):-
	recFila1(L1,0,L2).
recFila1([r|A],C,L2):-
	recFila1(A,s(C),L2).
recFila1([am|A],C,L2):-
	recFila1(A,s(C),L2).
recFila1([a|A],C,L2):-
	recFila1(A,s(C),L2).
recFila1([v|A],C,L2):-
	recFila1(A,s(C),L2).
recFila1([b|A],C,L2):-
	recFila1(A,C,L2).
recFila1([],C,L2) :-
	recFila2(L2,C,0).

recFila2([r|A],C1,C2):-
	recFila2(A,C1,s(C2)).
recFila2([am|A],C1,C2):-
	recFila2(A,C1,s(C2)).
recFila2([a|A],C1,C2):-
	recFila2(A,C1,s(C2)).
recFila2([v|A],C1,C2):-
	recFila2(A,C1,s(C2)).
recFila2([b|A],C1,C2):-
	recFila2(A,C1,C2).
recFila2([],C1,C2) :-
	menor(C1,C2).