less(0,s(X)):-nat(X).
less(0,0).
less(s(X),s(Y)):-less(X,Y).
eq(s(X),s(Y)):-eq(X,Y).
eq(0,0).
nat(0).
nat(s(X)):-nat(X).
dim(s(X)):-dim(X).
dim(s(0)).
pieza(X,Y,Z,C) :- dim(X),dim(Y),dim(Z),color(C).
color(r).
color(am).
color(a).
color(v).
esTorre([G|K]):-
	esMayor(G,K).
esMayor(pieza(X,Y,Z,C),[pieza(Q,W,E,R)|K]):-
	less(X,Q),less(Z,E),esMayor(pieza(Q,W,E,R),K),pieza(X,Y,Z,C),pieza(Q,W,E,R).
esMayor(pieza(X,Y,Z,C),[]):-pieza(X,Y,Z,C).	
alturaTorre(T,A):-esTorre(T),nat(A),sumaAltura(T,A).
sumaAltura([S|B],A):-sumRec(S,B,0,A).
sumRec(pieza(X,Y,Z,C),[pieza(Q,W,E,R)|K],P,A):-
	sum(Y,P,J),sumRec(pieza(Q,W,E,R),K,J,A),pieza(X,Y,Z,C),pieza(Q,W,E,R).
sumRec(pieza(X,Y,Z,C),[],P,A):-pieza(X,Y,Z,C),sum(Y,P,J),eq(J,A).
sum(0,Y,Y):-nat(Y).
sum(s(X),Y,s(Z)):-sum(X,Y,Z).
coloresTorre([pieza(X,Y,Z,C)|R],[V|B]):-
	pieza(X,Y,Z,C),C=V,coloresTorre(R,B).
coloresTorre([],[]).
coloresIncluidos(L,T):-
	esTorre(L),esTorre(T),colorSub(L,T,T).
colorSub(A,[_|Ys],T):-
	colorSub(A,Ys,T).
colorSub([pieza(_,_,_,X)|Xs],[pieza(_,_,_,X)|_],T):-
	colorSub(Xs,T,T).
colorSub([],_,_).
esPar(s(s(X))):-esPar(X).
esPar(0).
esEdificioPar([A|B]):-
	recFila(A,0),esEdificioPar(B).
esEdificioPar([]).

recFila([r|A],C):-
	recFila(A,s(C)).
recFila([am|A],C):-
	recFila(A,s(C)).
recFila([a|A],C):-
	recFila(A,s(C)).
recFila([v|A],C):-
	recFila(A,s(C)).
recFila([b|A],C):-
	recFila(A,C).
recFila([],C):-
	esPar(C).
	